import uuid
from datetime import datetime, timezone
from enum import Enum as PyEnum
from sqlalchemy import String, Integer, DateTime, Enum, ForeignKey, LargeBinary
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

# Using absolute import based on the root path setup in Phase 1
from db.session import Base

class UserRole(str, PyEnum):
    """
    Defines strict roles within the system as per the SRS requirement FR-01.
    Includes SUPERADMIN for platform-wide analytics and oversight.
    """
    STUDENT = "Student"
    TEACHER = "Teacher"
    SUPERADMIN = "SUPERADMIN"

class User(Base):
    __tablename__ = "users"

    # Core identification
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True, nullable=False)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[UserRole] = mapped_column(Enum(UserRole), nullable=False, default=UserRole.STUDENT)
    
    # Profile preferences (Specifically for students defining their study pace)
    weekly_hours: Mapped[int] = mapped_column(Integer, nullable=True)

    # =======================================================================
    # ENTERPRISE GAMIFICATION ENGINE (Phase 3)
    # =======================================================================
    current_streak: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    max_streak: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    points: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    last_activity_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)

    # Audit timestamps for tracking activity
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), 
        default=lambda: datetime.now(timezone.utc), 
        onupdate=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    # If a user is deleted, cascade the deletion to avoid orphaned records
    roadmaps = relationship("Roadmap", back_populates="student", cascade="all, delete-orphan")
    progress_records = relationship("Progress", back_populates="student", cascade="all, delete-orphan")
    
    # WebAuthn (Passkeys) for Face Login / Biometrics
    webauthn_credentials = relationship("WebAuthnCredential", back_populates="user", cascade="all, delete-orphan")
    notes = relationship("Note", back_populates="owner", cascade="all, delete-orphan")


class WebAuthnCredential(Base):
    """
    Stores hardware-bound public keys (FaceID, TouchID, YubiKey) for passwordless authentication.
    """
    __tablename__ = "webauthn_credentials"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    # The unique identifier for the credential generated by the authenticator
    credential_id: Mapped[bytes] = mapped_column(LargeBinary, unique=True, index=True, nullable=False)
    # The public key associated with the credential for cryptographic verification
    public_key: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    
    # Sign count to prevent credential cloning attacks
    sign_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    user = relationship("User", back_populates="webauthn_credentials")