import uuid
from datetime import datetime
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, ConfigDict

# Importing Enums from our database models
from models.roadmap import TaskType, TaskStatus

# ==============================================================================
# 1. AI Output JSON Validation Schemas (LangGraph/Azure OpenAI Guardrails)
# ==============================================================================

class AITaskDetail(BaseModel):
    """
    Validates a single task generated by the LLM.
    Ensures the AI assigns a correct TaskType (Resource, Quiz, or Coding).
    """
    title: str = Field(..., description="Specific topic or task title")
    description: str = Field(..., description="Brief explanation of what the student will learn or do")
    task_type: TaskType = Field(..., description="Categorization of the learning task")
    estimated_hours: float = Field(..., description="Estimated time required to complete this specific task")

class AIMilestone(BaseModel):
    """
    Validates a weekly milestone block generated by the LLM.
    """
    week_number: int = Field(..., description="Week sequence number")
    milestone_title: str = Field(..., description="Main objective or theme for the week")
    tasks: List[AITaskDetail] = Field(..., description="List of specific tasks assigned for this week")

class AIRoadmapGeneration(BaseModel):
    """
    The master schema passed to LangChain/LangGraph.
    The LLM is strictly prompted to return its JSON matching this exact structure.
    """
    target_domain: str = Field(..., description="The main learning subject, e.g., 'Full-Stack Web Development'")
    total_weeks: int = Field(..., description="Total duration of the generated roadmap")
    milestones: List[AIMilestone] = Field(..., description="Weekly breakdown of the customized curriculum")


# ==============================================================================
# 2. API Endpoint Schemas (Frontend Communication)
# ==============================================================================

class RoadmapGenerateRequest(BaseModel):
    """
    Payload received from the React frontend when a student clicks 'Generate Roadmap'[cite: 146].
    """
    target_domain: str = Field(..., description="What the student specifically wants to learn")
    weekly_hours: int = Field(..., gt=0, le=168, description="Hours the student can dedicate per week [cite: 146]")
    skill_level: str = Field(..., description="Derived from the Pre-Assessment score (e.g., Beginner, Intermediate) [cite: 146]")

class TaskResponse(BaseModel):
    """
    Schema for rendering individual tasks on the frontend timeline.
    """
    id: uuid.UUID
    title: str
    description: Optional[str] = None
    task_type: TaskType
    status: TaskStatus
    
    model_config = ConfigDict(from_attributes=True)

class RoadmapResponse(BaseModel):
    """
    Standard output for the roadmap data, combining the JSONB content and the relational tasks.
    """
    id: uuid.UUID
    student_id: uuid.UUID
    content: Dict[str, Any]  # The raw JSONB content validated against AIRoadmapGeneration
    is_active: bool
    created_at: datetime
    tasks: List[TaskResponse] = []  # Relational mapped tasks

    model_config = ConfigDict(from_attributes=True)