import operator
from typing import TypedDict, Annotated, List, Optional, Dict, Any
from langchain_core.messages import BaseMessage

class CurriculumState(TypedDict):
    """
    The central state object representing the shared memory across all LangGraph agents.
    It tracks the user's constraints, the evolving roadmap, and feedback loops.
    """
    
    # Message history for the LLMs context (appends new messages automatically)
    messages: Annotated[List[BaseMessage], operator.add]
    
    # User-defined constraints from the database
    target_domain: str
    weekly_hours: int
    skill_level: str
    
    # The JSON structure generated by the Architect agent
    draft_roadmap: Optional[Dict[str, Any]]
    
    # The final enriched roadmap after the Curator agent adds Pinecone resources
    final_roadmap: Optional[Dict[str, Any]]
    
    # Remediation and QA tracking (appends feedback on each iteration)
    reviewer_feedback: Annotated[List[str], operator.add]
    is_approved: bool
    
    # Enterprise Guardrails: Prevent infinite AI loops to save Azure API credits
    revision_count: int
    
    # System-level error tracking during agent executions
    errors: Annotated[List[str], operator.add]